package com.userfront.service.UserServiceImpl;

import com.userfront.service.EmailService;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Service;

import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.time.LocalDate;
import java.util.Date;
import java.util.Properties;

@Service
public class EmailServiceImpl implements EmailService {
    private final String from = "onlinebank@verejanbank.email.com";
    private final String host = "smtp.mailtrap.io";
    private final Properties properties = System.getProperties();
    private final Session session;
    private final String username = "1bc299aed746d1"; //username generated by Mailtrap
    private final String password = "75aab7de5f5c02";

    public EmailServiceImpl() {
        properties.setProperty("mail.smtp.host", host);
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.starttls.enable", "true");//it’s optional in Mailtrap
        properties.put("mail.smtp.host", host);
        properties.put("mail.smtp.port", "2525");// use one of the options in the SMTP settings tab in your Mailtrap Inbox
        session = Session.getInstance(properties,
                new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(username, password);
                    }
                });
    }

    @Override
    public void sendEmail(String to, int accountNumber, String username, String password) {
        try {
            // Create a default MimeMessage object.
            MimeMessage message = new MimeMessage(session);

            // Set From: header field of the header.
            message.setFrom(new InternetAddress(from));

            // Set To: header field of the header.
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to));

            // Set Subject: header field
            message.setSubject("Congratulations, an account was created for online banking");

            // Now set the actual message
            message.setText("Welcome on Board! dear user\nan account was created for " + to
                    + "\n" + "with username: " + username
                    + "\n" + "and password: " + password
                    + "\n" + "with account number: "
                    + accountNumber);

            // Send message
            Transport.send(message);
            System.out.println("Sent message successfully....");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void sendAppointmentEmail(String email, int accountNumber, String description, Date date) {
        try {
            // Create a default MimeMessage object.
            MimeMessage message = new MimeMessage(session);

            // Set From: header field of the header.
            message.setFrom(new InternetAddress(from));

            // Set To: header field of the header.
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(email));

            // Set Subject: header field
            message.setSubject("Congratulations, an appointment was created for online banking");

            // Now set the actual message
            message.setText("Welcome on Board! dear user\nan appointment was created for " + email
                    + "\n" + description + " on date: " + date.toString()
                    + "\n" + "with account number: "
                    + accountNumber);

            // Send message
            Transport.send(message);
            System.out.println("Sent message successfully....");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
